spring.application.name=mvc
# Configuración de la base de datos en memoria
spring.datasource.url=jdbc:h2:mem:carritodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permitir ver la consola de la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar las consultas SQL en la consola (muy útil para el examen)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
